domain_name: 'chouette.mobi'
secret_key_base: 'SECRET_KEY'
devise_secret_key: 'SECRET_KEY'
api_endpoint: 'http://localhost:8080/chouette_iev/'
google_analytic_tracker:
geoportail_api_key:
newrelic_licence_key:
osrm_endpoint: 'http://router.project-osrm.org'
app_version: 'Latest Docker 3.3.0'
deactivate_formats_referential: # For example: 'hub,sig,neptune'
deactivate_formats_import: # For example: 'hub,sig,neptune'
deactivate_formats_export: # For example: 'hub,sig,neptune'
smtp_delivery_method: 'smtp'
smtp_host: 'smtp'
smtp_port: '25'
smtp_domain:
smtp_user_name:
smtp_password:
smtp_authentication:
mailer_sender: 'no-reply@chouette.mobi'
capistrano_deploy_user:
