domain_name: 'localhost:3000'
secret_key_base: '04f58176594e0570ef0cdf42973ec230dc60a07142a41c9efc4eda572633bde3c16ed3d7c1828800a808e15cbaef5894a31354a18172d9995'
devise_secret_key: '04f58176594e0570ef0cdf42973ec230dc60a07142a41c9efc4eda572633bde3c16ed3d7c1828800a808e15cbaef5894a31354a18172d9995'
api_endpoint: 'http://chouette-iev:8080/chouette_iev/'
osrm_endpoint: 'http://router.project-osrm.org'
prefix_application_version: 'Latest Docker'
deactivate_formats_referential: 'hub,sig'
deactivate_formats_import: 'hub,sig'
deactivate_formats_export: 'hub,sig'
smtp_delivery_method: 'smtp'
smtp_host: 'smtp'
smtp_port: '25'
smtp_domain:
smtp_user_name:
smtp_password:
smtp_authentication:
mailer_sender: 'no-reply@chouette.mobi'

